<a href="https://colab.research.google.com/github/alik604/Notebooks/blob/master/Data%20Science-Datasets/pima%20indians%20diabetes%20dataset/Diabetes_Prediction_cleaned_up_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://en.wikipedia.org/wiki/Decision_tree_learning#Decision_tree_types
https://en.wikipedia.org/wiki/Decision_tree_learning#Metrics

https://www.datacamp.com/community/tutorials/decision-tree-classification-python

images 
https://scikit-learn.org/stable/modules/tree.html


### regressor vs classifier: 
https://math.stackexchange.com/a/183001

https://www.kaggle.com/pouryaayria/a-complete-ml-pipeline-tutorial-acu-86

https://www.kaggle.com/shrutimechlearn/step-by-step-diabetes-classification-knn-detailed

https://www.kaggle.com/ash316/ml-from-scratch-part-2

In [1]:
import numpy as np
import scipy 
import pandas as pd 

from sklearn.metrics import accuracy_score #Import scikit-learn metrics module for accuracy calculation


from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split # Import train_test_split function


from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier,export_graphviz # Import Decision Tree Classifier
from sklearn.ensemble import RandomForestClassifier,VotingClassifier, GradientBoostingClassifier
from sklearn.svm import SVC,SVR,LinearSVR,LinearSVC
from sklearn.naive_bayes import GaussianNB,BernoulliNB,BaseDiscreteNB,ComplementNB,MultinomialNB

from sklearn.externals.six import StringIO  
from IPython.display import Image  


from matplotlib import pyplot as plt

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)

In [2]:
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']

# load dataset
pima = pd.read_csv('https://raw.githubusercontent.com/alik604/Notebooks/master/Data%20Science-Datasets/pima%20indians%20diabetes%20dataset/diabetes.csv' ,header=1, names=col_names,error_bad_lines=False)
pima.head(10)

   pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0         1       85  66    29        0  26.6     0.351   31      0
1         8      183  64     0        0  23.3     0.672   32      1
2         1       89  66    23       94  28.1     0.167   21      0
3         0      137  40    35      168  43.1     2.288   33      1
4         5      116  74     0        0  25.6     0.201   30      0
5         3       78  50    32       88  31.0     0.248   26      1
6        10      115   0     0        0  35.3     0.134   29      0
7         2      197  70    45      543  30.5     0.158   53      1
8         8      125  96     0        0   0.0     0.232   54      1
9         4      110  92     0        0  37.6     0.191   30      0

In [3]:
pima.describe()

         pregnant     glucose          bp  ...    pedigree         age       label
count  767.000000  767.000000  767.000000  ...  767.000000  767.000000  767.000000
mean     3.842243  120.859192   69.101695  ...    0.471674   33.219035    0.348110
std      3.370877   31.978468   19.368155  ...    0.331497   11.752296    0.476682
min      0.000000    0.000000    0.000000  ...    0.078000   21.000000    0.000000
25%      1.000000   99.000000   62.000000  ...    0.243500   24.000000    0.000000
50%      3.000000  117.000000   72.000000  ...    0.371000   29.000000    0.000000
75%      6.000000  140.000000   80.000000  ...    0.625000   41.000000    1.000000
max     17.000000  199.000000  122.000000  ...    2.420000   81.000000    1.000000

[8 rows x 9 columns]

In [4]:
pima.astype(float)
pima.corr()

          pregnant   glucose        bp  ...  pedigree       age     label
pregnant  1.000000  0.128846  0.141197  ... -0.033927  0.544018  0.221087
glucose   0.128846  1.000000  0.152498  ...  0.136903  0.262408  0.465856
bp        0.141197  0.152498  1.000000  ...  0.041180  0.239571  0.064882
skin     -0.082495  0.056381  0.207308  ...  0.183498 -0.115873  0.073265
insulin  -0.072999  0.332383  0.089098  ...  0.185579 -0.040942  0.131984
bmi       0.017518  0.220955  0.281777  ...  0.140546  0.035911  0.292695
pedigree -0.033927  0.136903  0.041180  ...  1.000000  0.032738  0.173245
age       0.544018  0.262408  0.239571  ...  0.032738  1.000000  0.236417
label     0.221087  0.465856  0.064882  ...  0.173245  0.236417  1.000000

[9 rows x 9 columns]

In [0]:
#split dataset in features and target variable
feature_cols = ['pregnant','glucose', 'insulin', 'bmi', 'pedigree','age']
# feature_cols = ['pregnant', 'insulin', 'bmi', 'age','glucose','bp','pedigree']
X = pima[feature_cols] # Features
y = pima.label # Target variable

# DecisionTreeClassifier

https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html
https://en.wikipedia.org/wiki/Decision_tree_learning#Metrics
https://medium.com/@mohtedibf/indepth-parameter-tuning-for-decision-tree-6753118a03c3

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1) # 70% training and 30% test

# Create Decision Tree classifer object
clf = DecisionTreeClassifier(criterion='gini')

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.7447916666666666

In [0]:
# from sklearn.externals.six import StringIO  
# from IPython.display import Image  
# from sklearn.tree import export_graphviz
# import pydotplus
# dot_data = StringIO()
# export_graphviz(clf, out_file=dot_data,  
#                 filled=True, rounded=True,
#                 special_characters=True, feature_names = feature_cols,class_names=['0','1'])
# graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
# graph.write_png('diabetes.png')
# Image(graph.create_png())

In [7]:
topI = 0
topY = 0
for i in range(1,40,1):
    clf = KNeighborsClassifier(i)
    clf = clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    score = accuracy_score(y_test, y_pred)
    if score > topY:
        topY=score
        topI = i
#     print("i: {0}, Accuracy: {1}".format(i,score))
print("BEST: i: {0}, Accuracy: {1}".format(topI,topY))

BEST: i: 4, Accuracy: 0.75

# RandomForestClassifier
https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

In [8]:
clf = RandomForestClassifier(criterion='entropy',max_depth=5)

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.75

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

## Ensembling with VotingClassifier
https://stats.stackexchange.com/questions/190151/ensembling-with-votingclassifier
https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.VotingClassifier.html#sklearn.ensemble.VotingClassifier

In [9]:
bestOfTen = []
for i in range(10):
  alg1 = RandomForestClassifier(criterion='entropy',max_depth=5) #ExtraTreesClassifier()
  alg2 = GradientBoostingClassifier()
  alg3 = KNeighborsClassifier(topI)

  eAlg = VotingClassifier(estimators=[('LR',alg1),('GB',alg2),('NB',alg3)],
                          voting='hard',
                          weights=[1,1,1])
  eAlg.fit(X_train,y_train)
  pred_ens = eAlg.predict(X_test)


  bestOfTen.append(np.mean(pred_ens == y_test) )
  
x= np.mean(bestOfTen)
x

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

0.7557291666666666

# SVM.SVC
https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html

https://en.wikipedia.org/wiki/Confusion_matrix

In [10]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)




#classifier = SVC(kernel = 'linear', random_state=0)
classifier = LinearSVC()

classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)
ac = accuracy_score(y_test, y_pred)
ac

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

0.7604166666666666

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

In [12]:
classifier = GaussianNB()
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)
ac = accuracy_score(y_test, y_pred)
ac

0.7662337662337663

# lets discard 'bad' rows

In [13]:
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']


pima = pd.read_csv('https://raw.githubusercontent.com/alik604/Notebooks/master/Data%20Science-Datasets/pima%20indians%20diabetes%20dataset/diabetes-cleanData.csv' ,header=1, names=col_names,error_bad_lines=False)

# keeping our fetures from above 
feature_cols = ['pregnant','glucose', 'insulin', 'bmi', 'pedigree','age']
X = pima[feature_cols] # Features
y = pima.label # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1) # 70% training and 30% test


pima.head(10)

   pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0        10      101  76    48      180  32.9     0.171   63      0
1         7      142  60    33      190  28.8     0.687   61      0
2         6      129  90     7      326  19.6     0.582   60      0
3         8      181  68    36      495  30.1     0.615   60      1
4         1      189  60    23      846  30.1     0.398   59      1
5         5      144  82    26      285  32.0     0.452   58      1
6         8      176  90    34      300  33.7     0.467   58      1
7        12      140  82    43      325  39.2     0.528   58      1
8         0      173  78    32      265  46.5     1.159   58      0
9        13      145  82    19      110  22.2     0.245   57      0

In [14]:

pima.head(10)

   pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0        10      101  76    48      180  32.9     0.171   63      0
1         7      142  60    33      190  28.8     0.687   61      0
2         6      129  90     7      326  19.6     0.582   60      0
3         8      181  68    36      495  30.1     0.615   60      1
4         1      189  60    23      846  30.1     0.398   59      1
5         5      144  82    26      285  32.0     0.452   58      1
6         8      176  90    34      300  33.7     0.467   58      1
7        12      140  82    43      325  39.2     0.528   58      1
8         0      173  78    32      265  46.5     1.159   58      0
9        13      145  82    19      110  22.2     0.245   57      0

In [15]:
pima.describe()

         pregnant     glucose          bp  ...    pedigree         age       label
count  388.000000  388.000000  388.000000  ...  388.000000  388.000000  388.000000
mean     3.193299  122.518041   70.634021  ...    0.523691   30.623711    0.327320
std      3.031490   30.917448   12.553558  ...    0.346376    9.845455    0.469841
min      0.000000   56.000000   24.000000  ...    0.085000   21.000000    0.000000
25%      1.000000   99.000000   62.000000  ...    0.269750   23.000000    0.000000
50%      2.000000  119.000000   70.000000  ...    0.449500   27.000000    0.000000
75%      5.000000  143.000000   78.000000  ...    0.687000   35.250000    1.000000
max     13.000000  198.000000  110.000000  ...    2.420000   63.000000    1.000000

[8 rows x 9 columns]

In [26]:
bestOfTen = []
for i in range(10):
  alg1 = RandomForestClassifier(criterion='entropy',max_depth=5) #ExtraTreesClassifier()
  alg2 = GradientBoostingClassifier()
  alg3 = KNeighborsClassifier(topI)

  eAlg = VotingClassifier(estimators=[('LR',alg1),('GB',alg2),('NB',alg3)],
                          voting='hard',
                          weights=[1,1,1])
  eAlg.fit(X_train,y_train)
  pred_ens = eAlg.predict(X_test)


  bestOfTen.append(np.mean(pred_ens == y_test) )
  
x= np.mean(bestOfTen)
x

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

0.7557291666666666

# lets fix 'bad' rows

In [17]:
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']


pima = pd.read_csv('https://raw.githubusercontent.com/alik604/Notebooks/master/Data%20Science-Datasets/pima%20indians%20diabetes%20dataset/diabetes.csv' ,header=1, names=col_names,error_bad_lines=False)

# keeping our fetures from above 
feature_cols = ['pregnant','glucose', 'insulin', 'bmi', 'pedigree','age']
X = pima[feature_cols] # Features
y = pima.label # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1) # 70% training and 30% test


pima.head(10)

   pregnant  glucose  bp  skin  insulin   bmi  pedigree  age  label
0         1       85  66    29        0  26.6     0.351   31      0
1         8      183  64     0        0  23.3     0.672   32      1
2         1       89  66    23       94  28.1     0.167   21      0
3         0      137  40    35      168  43.1     2.288   33      1
4         5      116  74     0        0  25.6     0.201   30      0
5         3       78  50    32       88  31.0     0.248   26      1
6        10      115   0     0        0  35.3     0.134   29      0
7         2      197  70    45      543  30.5     0.158   53      1
8         8      125  96     0        0   0.0     0.232   54      1
9         4      110  92     0        0  37.6     0.191   30      0

In [18]:
pima.describe()

         pregnant     glucose          bp  ...    pedigree         age       label
count  767.000000  767.000000  767.000000  ...  767.000000  767.000000  767.000000
mean     3.842243  120.859192   69.101695  ...    0.471674   33.219035    0.348110
std      3.370877   31.978468   19.368155  ...    0.331497   11.752296    0.476682
min      0.000000    0.000000    0.000000  ...    0.078000   21.000000    0.000000
25%      1.000000   99.000000   62.000000  ...    0.243500   24.000000    0.000000
50%      3.000000  117.000000   72.000000  ...    0.371000   29.000000    0.000000
75%      6.000000  140.000000   80.000000  ...    0.625000   41.000000    1.000000
max     17.000000  199.000000  122.000000  ...    2.420000   81.000000    1.000000

[8 rows x 9 columns]

In [19]:
pima= pima.astype(float)
pima.corr()

          pregnant   glucose        bp  ...  pedigree       age     label
pregnant  1.000000  0.128846  0.141197  ... -0.033927  0.544018  0.221087
glucose   0.128846  1.000000  0.152498  ...  0.136903  0.262408  0.465856
bp        0.141197  0.152498  1.000000  ...  0.041180  0.239571  0.064882
skin     -0.082495  0.056381  0.207308  ...  0.183498 -0.115873  0.073265
insulin  -0.072999  0.332383  0.089098  ...  0.185579 -0.040942  0.131984
bmi       0.017518  0.220955  0.281777  ...  0.140546  0.035911  0.292695
pedigree -0.033927  0.136903  0.041180  ...  1.000000  0.032738  0.173245
age       0.544018  0.262408  0.239571  ...  0.032738  1.000000  0.236417
label     0.221087  0.465856  0.064882  ...  0.173245  0.236417  1.000000

[9 rows x 9 columns]

In [20]:
X_train= X_train.replace(0, np.nan)
X_train=X_train.apply(lambda x: x.fillna(x.mean()),axis=0)
X_train.head(12)

     pregnant  glucose     insulin   bmi  pedigree  age
118       4.0     99.0   51.000000  23.2     0.223   21
205       8.0    196.0  280.000000  37.5     0.605   57
506       1.0    130.0  170.000000  28.6     0.692   21
587       3.0    176.0  156.000000  33.3     1.154   52
34        4.0    103.0  192.000000  24.0     0.966   33
257       1.0    193.0  375.000000  25.9     0.655   24
216       6.0    125.0  120.000000  30.0     0.464   32
598       1.0    109.0  120.000000  23.1     0.407   26
760       9.0    170.0  156.221477  44.0     0.403   43
160       7.0    102.0  105.000000  37.2     0.204   45
713       3.0    102.0  156.221477  29.5     0.121   32
372       2.0    105.0   94.000000  34.9     0.225   25

In [28]:
bestOfTen = []
for i in range(20):
  alg1 = RandomForestClassifier(criterion='entropy',max_depth=5) #ExtraTreesClassifier()
  alg2 = GradientBoostingClassifier()
  alg3 = KNeighborsClassifier(topI)

  eAlg = VotingClassifier(estimators=[('LR',alg1),('GB',alg2),('NB',alg3)],
                          voting='hard',
                          weights=[1,1,1])
  eAlg.fit(X_train,y_train)
  pred_ens = eAlg.predict(X_test)


  bestOfTen.append(np.mean(pred_ens == y_test) )
  
x= np.mean(bestOfTen)
x

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

0.7567708333333333